export const FETCH_GLOBAL_COINS_DATA_PENDING =
  "FETCH_GLOBAL_COINS_DATA_PENDING";
export const FETCH_GLOBAL_COINS_DATA_SUCCESS =
  "FETCH_GLOBAL_COINS_DATA_SUCCESS";
export const FETCH_GLOBAL_COINS_DATA_ERROR = "FETCH_GLOBAL_COINS_DATA_ERROR";
